apiVersion: v1
kind: ConfigMap
metadata:
  name: control-plane-config
  namespace: cloud-nlb
data:
  GRPC_SERVER_PORT: "9090"
  GRPC_SERVER_ADDR: "0.0.0.0"
  HEALTH_PORT: "8080"
  LOGGER_LEVEL: "INFO"
  DEBUG: "true"


  ETCD_ENDPOINT: "192.168.5.2:2379"
  ETCD_RUNTIME_MAC_CONCURRENCY: "10"

  DATA_PLANE_SUBSCRIBE_GC_INTERVAL: "15s"

  CACHE_GC_INTERVAL: "60s"

  GRPC_MAX_CONNECTION_IDLE: "300s"
  GRPC_MAX_CONNECTION_AGE: "3600s"
  GRPC_KEEPALIVE_TIME: "60s"
  GRPC_KEEPALIVE_TIMEOUT: "20s"